spring:
    datasource:
        url: jdbc:mysql://${DB_URL:localhost}:${DB_PORT:3306}/${DB_DATABASE:voting}
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:root}
    jpa:
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: none
    flyway:
        enabled: ${FLYWAY_ENABLED:true}
        schemas: ${DB_DATABASE:voting}
        user:  ${DB_USERNAME:root}
        password: ${DB_PASSWORD:root}

server:
    servlet:
        context-path: /voting